plugins:
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme

readme_index:
  enabled: false

theme: just-the-docs

exclude:
  - Gemfile
  - Gemfile.lock
  - build_scripts
  - "*.bat"
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

markdown: kramdown
kramdown:
  parse_block_html: true

baseurl: "/foo_discord_rich/"
url: "https://s0hv.github.io"
username: s0hv

permalink: pretty

title: Discord Rich Presence Integration

aux_links:
  "View on GitHub":
    - "//github.com/s0hv/foo_discord_rich"

color_scheme: "dark"

footer_content: "Copyright &copy; 2018-2023 Yuri Shutenko, s0hv.<br/>Distributed by an <a href=\"https://github.com/s0hv/foo_discord_rich/blob/master/LICENSE\">MIT license.</a>"

ga_tracking: UA-154231909-3
